USE WAREHOUSE PROJECT_10_WH;
USE DATABASE PROJECT_10_DB;
USE SCHEMA PROJECT_10_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE='CSV'
SKIP_HEADER=1;

CREATE OR REPLACE STAGE CUSTOMER_STAGE
FILE_FORMAT=CSV_FORMAT;

------------TABLE CREATION AND UPLOADING
CREATE OR REPLACE TABLE RAW_CUSTOMERS(
CUSTOMER_ID NUMBER,
CUSTOMER_NAME VARCHAR,
CITY VARCHAR,
STATE VARCHAR,
MEMBERSHIP VARCHAR,
SEGMENT VARCHAR
);

LIST @CUSTOMER_STAGE;

COPY INTO RAW_CUSTOMERS
FROM @CUSTOMER_STAGE/customer_initial1.csv
FILE_FORMAT=CSV_FORMAT;

------------SCD TYPE 3 CREATION
CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE3 (
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    CURRENT_MEMBERSHIP VARCHAR,
    PREVIOUS_MEMBERSHIP VARCHAR,
    SEGMENT VARCHAR
);

INSERT INTO DIM_CUSTOMER_TYPE3
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    NULL,
    SEGMENT
FROM RAW_CUSTOMERS;
------------------validation
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;

Select * from DIM_CUSTOMER_TYPE3;

-------------------CREATING AND LOADING CUSTOMER_UPDATES

CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    MEMBERSHIP VARCHAR,
    SEGMENT VARCHAR,
    EFFECTIVE_DATE DATE
);

COPY INTO CUSTOMER_UPDATES
FROM @CUSTOMER_STAGE/customer_update1.csv
FILE_FORMAT = CSV_FORMAT;

--------------------APPLYING SCD TYPE 3 CHANGES
UPDATE DIM_CUSTOMER_TYPE3 T
SET
    PREVIOUS_MEMBERSHIP = T.CURRENT_MEMBERSHIP,
    CURRENT_MEMBERSHIP = U.MEMBERSHIP,
    CITY = U.CITY,
    STATE = U.STATE,
    SEGMENT = U.SEGMENT
FROM CUSTOMER_UPDATES U
WHERE T.CUSTOMER_ID = U.CUSTOMER_ID
  AND T.CURRENT_MEMBERSHIP <> U.MEMBERSHIP;

----------------type 3 final report
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;

--------------------CREATING TYPE 6 DIMENSION
CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE6 (
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    CURRENT_MEMBERSHIP VARCHAR,
    PREVIOUS_MEMBERSHIP VARCHAR,
    HISTORICAL_MEMBERSHIP VARCHAR,
    SEGMENT VARCHAR,
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);
------------------LOADING DATA
INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    NULL,
    MEMBERSHIP,
    SEGMENT,
    '2026-01-01',
    '9999-12-31',
    TRUE
FROM RAW_CUSTOMERS;

-------------------VALIDATING
SELECT *
FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID;

----------------CHANGE FOR 101
UPDATE DIM_CUSTOMER_TYPE6 T
SET
    EXPIRY_DATE = DATEADD(DAY, -1, U.EFFECTIVE_DATE),
    IS_CURRENT = FALSE
FROM CUSTOMER_UPDATES U
WHERE T.CUSTOMER_ID = U.CUSTOMER_ID
  AND T.IS_CURRENT = TRUE;


INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    U.CUSTOMER_ID,
    U.CUSTOMER_NAME,
    U.CITY,
    U.STATE,
    U.MEMBERSHIP,
    T.CURRENT_MEMBERSHIP,
    U.MEMBERSHIP,
    U.SEGMENT,
    U.EFFECTIVE_DATE,
    '9999-12-31',
    TRUE
FROM CUSTOMER_UPDATES U
JOIN DIM_CUSTOMER_TYPE6 T
    ON U.CUSTOMER_ID = T.CUSTOMER_ID
WHERE T.IS_CURRENT = FALSE
  AND T.EXPIRY_DATE = DATEADD(DAY, -1, U.EFFECTIVE_DATE);

--------------VALIDATION
Select * from DIM_CUSTOMER_TYPE6
Order by CUSTOMER_ID,EFFECTIVE_DATE;

----------------CHANGE FOR 103 AND 104(actually wrong)
INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    NULL,
    MEMBERSHIP,
    SEGMENT,
    '2026-01-01',
    '9999-12-31',
    TRUE
FROM RAW_CUSTOMERS
WHERE CUSTOMER_ID IN (103, 104);


---------------VALIDATING COMPLETE TABLE
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

------------------------DEBUGGING THE MISTAKE
SELECT
    CUSTOMER_ID,
    CUSTOMER_KEY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID IN (103, 104)
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE, CUSTOMER_KEY;

-------------------------deleting those records

DELETE FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID IN (103, 104);

-------------------fixing the table by inserting older records
INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    NULL,
    MEMBERSHIP,
    SEGMENT,
    '2026-01-01',
    '9999-12-31',
    TRUE
FROM RAW_CUSTOMERS
WHERE CUSTOMER_ID IN (103, 104);

----------------closing old records
UPDATE DIM_CUSTOMER_TYPE6 T
SET
    EXPIRY_DATE = DATEADD(DAY, -1, U.EFFECTIVE_DATE),
    IS_CURRENT = FALSE
FROM CUSTOMER_UPDATES U
WHERE T.CUSTOMER_ID = U.CUSTOMER_ID
  AND T.IS_CURRENT = TRUE
  AND U.CUSTOMER_ID IN (103, 104);

----------------------------inserting new records
INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    U.CUSTOMER_ID,
    U.CUSTOMER_NAME,
    U.CITY,
    U.STATE,
    U.MEMBERSHIP,
    T.CURRENT_MEMBERSHIP,
    U.MEMBERSHIP,
    U.SEGMENT,
    U.EFFECTIVE_DATE,
    '9999-12-31',
    TRUE
FROM CUSTOMER_UPDATES U
JOIN DIM_CUSTOMER_TYPE6 T
    ON U.CUSTOMER_ID = T.CUSTOMER_ID
WHERE T.IS_CURRENT = FALSE
  AND T.EXPIRY_DATE = DATEADD(DAY, -1, U.EFFECTIVE_DATE)
  AND U.CUSTOMER_ID IN (103, 104);

  -------------------validating complete table
  SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;


-- Now management wants only the current status of every customer.
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

-- What was Customer 101's membership on March 15, 2026?
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 101
  AND '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

-- Type 6 current record count

SELECT COUNT(*) AS SCD_TYPE6_CURRENT_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE;

-- Type 6 historical record count

SELECT COUNT(*) AS SCD_TYPE6_HISTORICAL_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = FALSE;

-- FINAL VALIDATION QUERY
SELECT
    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_TYPE3) AS SCD_TYPE3_RECORD_COUNT,

    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_TYPE6) AS SCD_TYPE6_RECORD_COUNT,

    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_TYPE6
     WHERE IS_CURRENT = TRUE) AS SCD_TYPE6_CURRENT_RECORD_COUNT,

    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_TYPE6
     WHERE IS_CURRENT = FALSE) AS SCD_TYPE6_HISTORICAL_RECORD_COUNT;