USE WAREHOUSE PROJECT_15_WH;
USE DATABASE PROJECT_15_DB;
USE SCHEMA PROJECT_15_SCHEMA;

-------FILE FORMAT CREATION
CREATE OR REPLACE FILE FORMAT IOT_FORMAT
TYPE=JSON;

----------INTERNAL STAGE
CREATE OR REPLACE STAGE IOT_RAW_STAGE
FILE_FORMAT=IOT_FORMAT;

-------------creating bronze table
CREATE OR REPLACE TABLE BRONZE_IOT_STREAMS
(
    INGEST_ID NUMBER AUTOINCREMENT,
    RAW_PAYLOAD VARIANT,
    RECORDED_AT TIMESTAMP
);

LIST @IOT_RAW_STAGE;

------------loading batch1
COPY INTO BRONZE_IOT_STREAMS
(
    RAW_PAYLOAD,
    RECORDED_AT
)
FROM
(
    SELECT
        $1,
        CURRENT_TIMESTAMP()
    FROM @IOT_RAW_STAGE/batch1.json
)
FILE_FORMAT = IOT_FORMAT;

----------loading batch2
COPY INTO BRONZE_IOT_STREAMS
(
    RAW_PAYLOAD,
    RECORDED_AT
)
FROM
(
    SELECT
        $1,
        CURRENT_TIMESTAMP()
    FROM @IOT_RAW_STAGE/batch2.json
)
FILE_FORMAT = IOT_FORMAT;

------------loading bacth3 

-------a.Creating a quarnatine table
CREATE OR REPLACE TABLE QUARANTINE_IOT_PAYLOADS
(
    QUARANTINE_ID NUMBER AUTOINCREMENT,
    RAW_RECORD_TEXT STRING,
    REASON STRING
);

----------b.file format creation
CREATE OR REPLACE FILE FORMAT IOT_TEXT_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = NONE
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 0;

-----------c.Read batch 3 as text
SELECT
    $1 AS RAW_RECORD_TEXT
FROM @IOT_RAW_STAGE/batch3.json
(
    FILE_FORMAT => 'IOT_TEXT_FORMAT'
);

--------d.APPLY TYR_PARSE_JSON
SELECT
    $1 AS RAW_RECORD_TEXT,
    TRY_PARSE_JSON($1) AS PARSED_JSON
FROM @IOT_RAW_STAGE/batch3.json
(
    FILE_FORMAT => 'IOT_TEXT_FORMAT'
);

-----------e.Loading the valid batch3 record into bronze
INSERT INTO BRONZE_IOT_STREAMS
(
    RAW_PAYLOAD,
    RECORDED_AT
)
SELECT
    TRY_PARSE_JSON($1),
    CURRENT_TIMESTAMP()
FROM @IOT_RAW_STAGE/batch3.json
(
    FILE_FORMAT => 'IOT_TEXT_FORMAT'
)
WHERE TRY_PARSE_JSON($1) IS NOT NULL;


-----------f.validating the count
SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS
FROM BRONZE_IOT_STREAMS;

---------g.Putting the invalid records into quarantinne
INSERT INTO QUARANTINE_IOT_PAYLOADS
(
    RAW_RECORD_TEXT,
    REASON
)
SELECT
    $1,
    'MALFORMED_JSON_BODY'
FROM @IOT_RAW_STAGE/batch3.json
(
    FILE_FORMAT => 'IOT_TEXT_FORMAT'
)
WHERE TRY_PARSE_JSON($1) IS NULL;

------------h.validating
SELECT *
FROM QUARANTINE_IOT_PAYLOADS;


-----------------SCHEMA-ON-READ EXPLORATION
SELECT
    RAW_PAYLOAD:payload_id::STRING AS PAYLOAD_ID,
    RAW_PAYLOAD:payload_type::STRING AS PAYLOAD_TYPE,
    RAW_PAYLOAD:timestamp::TIMESTAMP AS EVENT_TIMESTAMP,
    RAW_PAYLOAD:data.vehicle_id::STRING AS VEHICLE_ID,
    RAW_PAYLOAD:data.shipment_id::STRING AS SHIPMENT_ID,
    RAW_PAYLOAD:data.declared_value::NUMBER(12,2) AS DECLARED_VALUE
FROM BRONZE_IOT_STREAMS
ORDER BY PAYLOAD_ID;

---------------Silver Layer ETL: Schema-on-Write

------------a.creating silver table
CREATE OR REPLACE TABLE SILVER_CUSTOMS_CLEARANCE
(
    SHIPMENT_ID         VARCHAR,
    PAYLOAD_ID          VARCHAR,
    VEHICLE_ID          VARCHAR,
    DESTINATION_COUNTRY VARCHAR,
    DECLARED_VALUE      NUMBER(12,2),
    DUTY_PCT             NUMBER(5,2),
    DUTY_AMOUNT_DUE      NUMBER(12,2),
    BORDER_CODE          VARCHAR,
    CLEARANCE_STATUS     VARCHAR
);

---------------b.Loading data into Silver table
INSERT INTO SILVER_CUSTOMS_CLEARANCE
(
    SHIPMENT_ID,
    PAYLOAD_ID,
    VEHICLE_ID,
    DESTINATION_COUNTRY,
    DECLARED_VALUE,
    DUTY_PCT,
    DUTY_AMOUNT_DUE,
    BORDER_CODE,
    CLEARANCE_STATUS
)
SELECT
    RAW_PAYLOAD:data.shipment_id::STRING AS SHIPMENT_ID,

    RAW_PAYLOAD:payload_id::STRING AS PAYLOAD_ID,

    RAW_PAYLOAD:data.vehicle_id::STRING AS VEHICLE_ID,

    RAW_PAYLOAD:data.destination_country::STRING AS DESTINATION_COUNTRY,

    RAW_PAYLOAD:data.declared_value::NUMBER(12,2) AS DECLARED_VALUE,

    RAW_PAYLOAD:data.duty_pct::NUMBER(5,2) AS DUTY_PCT,

    (
        RAW_PAYLOAD:data.declared_value::NUMBER(12,2)
        *
        RAW_PAYLOAD:data.duty_pct::NUMBER(5,2)
        / 100
    )::NUMBER(12,2) AS DUTY_AMOUNT_DUE,

    RAW_PAYLOAD:data.border_clearance_code::STRING AS BORDER_CODE,

    RAW_PAYLOAD:data.clearance_status::STRING AS CLEARANCE_STATUS

FROM BRONZE_IOT_STREAMS

WHERE RAW_PAYLOAD:payload_type::STRING = 'CUSTOMS';

-----------c.Validating
SELECT *
FROM SILVER_CUSTOMS_CLEARANCE
ORDER BY SHIPMENT_ID;

--------------d.Demonstrates the schema evolution.(This demonstrates how the new border_clearance_code field introduced in Batch 2 is incorporated into the structured Silver model)
SELECT
    SHIPMENT_ID,
    BORDER_CODE
FROM SILVER_CUSTOMS_CLEARANCE
ORDER BY SHIPMENT_ID;

----------------GOLD LAYER:STRATEGIC AGGREGATION

-----------------a.Creating gold table
CREATE OR REPLACE TABLE GOLD_COUNTRY_DUTY_SUMMARY
(
    DESTINATION_COUNTRY VARCHAR,
    TOTAL_DECLARED_VALUE NUMBER(14,2),
    TOTAL_DUTY_AMOUNT    NUMBER(14,2),
    AVG_DUTY_RATE_PCT    NUMBER(6,2)
);

----------b.Loading Data
INSERT INTO GOLD_COUNTRY_DUTY_SUMMARY
(
    DESTINATION_COUNTRY,
    TOTAL_DECLARED_VALUE,
    TOTAL_DUTY_AMOUNT,
    AVG_DUTY_RATE_PCT
)
SELECT
    DESTINATION_COUNTRY,
    SUM(DECLARED_VALUE) AS TOTAL_DECLARED_VALUE,
    SUM(DUTY_AMOUNT_DUE) AS TOTAL_DUTY_AMOUNT,

    ROUND(
        SUM(DUTY_AMOUNT_DUE)
        / NULLIF(SUM(DECLARED_VALUE), 0)
        * 100,
        2
    ) AS AVG_DUTY_RATE_PCT

FROM SILVER_CUSTOMS_CLEARANCE

WHERE CLEARANCE_STATUS = 'CLEARED'

GROUP BY DESTINATION_COUNTRY

ORDER BY DESTINATION_COUNTRY;

----------- c.Verify Gold table
SELECT *
FROM GOLD_COUNTRY_DUTY_SUMMARY
ORDER BY DESTINATION_COUNTRY;

-------------TIME TRAVEL
-- UPDATE SILVER_CUSTOMS_CLEARANCE
-- SET CLEARANCE_STATUS = 'HOLD'
-- WHERE DESTINATION_COUNTRY = 'USA'
--   AND CLEARANCE_STATUS = 'CLEARED';

  SELECT
    SHIPMENT_ID,
    PAYLOAD_ID,
    VEHICLE_ID,
    DESTINATION_COUNTRY,
    DECLARED_VALUE,
    DUTY_AMOUNT_DUE,
    CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
ORDER BY SHIPMENT_ID;

------------a.accidental update
UPDATE SILVER_CUSTOMS_CLEARANCE
SET CLEARANCE_STATUS = 'REJECTED'
WHERE DESTINATION_COUNTRY = 'CAN';

-------------b.verifying the corruption
SELECT
    SHIPMENT_ID,
    DESTINATION_COUNTRY,
    CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
WHERE DESTINATION_COUNTRY = 'CAN'
ORDER BY SHIPMENT_ID;

-----------------c.Time Travel Inspection
SELECT
    SHIPMENT_ID,
    DESTINATION_COUNTRY,
    CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
BEFORE (
    STATEMENT => '01c6dc9d-3203-4aa4-0017-f2ea0027cb8a'
)
WHERE DESTINATION_COUNTRY = 'CAN'
ORDER BY SHIPMENT_ID;

------------d.Recovery by creating another temp table
CREATE OR REPLACE TEMP TABLE CAN_RECOVERY_SNAPSHOT AS
SELECT
    SHIPMENT_ID,
    CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
BEFORE (
    STATEMENT => '01c6dc9d-3203-4aa4-0017-f2ea0027cb8a'
)
WHERE DESTINATION_COUNTRY = 'CAN';

----------e.verifying
SELECT *
FROM CAN_RECOVERY_SNAPSHOT
ORDER BY SHIPMENT_ID;

------------f.Final updating in main table
UPDATE SILVER_CUSTOMS_CLEARANCE AS S
SET CLEARANCE_STATUS = R.CLEARANCE_STATUS
FROM CAN_RECOVERY_SNAPSHOT AS R
WHERE S.SHIPMENT_ID = R.SHIPMENT_ID;

------------FINAL AUDIT
SELECT
    DESTINATION_COUNTRY,
    COUNT_IF(CLEARANCE_STATUS = 'CLEARED') AS CLEARED_COUNT,
    COUNT_IF(CLEARANCE_STATUS = 'REJECTED') AS REJECTED_COUNT
FROM SILVER_CUSTOMS_CLEARANCE
GROUP BY DESTINATION_COUNTRY
ORDER BY DESTINATION_COUNTRY;

------------FINAL Reconciliation Query
WITH BRONZE_TOTAL AS
(
    SELECT
        SUM(
            RAW_PAYLOAD:data.declared_value::NUMBER(12,2)
        ) AS BRONZE_GROSS_TOTAL
    FROM BRONZE_IOT_STREAMS
    WHERE RAW_PAYLOAD:payload_type::STRING = 'CUSTOMS'
),

SILVER_TOTAL AS
(
    SELECT
        SUM(DECLARED_VALUE) AS SILVER_GROSS_TOTAL
    FROM SILVER_CUSTOMS_CLEARANCE
),

GOLD_TOTAL AS
(
    SELECT
        SUM(TOTAL_DECLARED_VALUE) AS GOLD_GROSS_TOTAL
    FROM GOLD_COUNTRY_DUTY_SUMMARY
)

SELECT
    B.BRONZE_GROSS_TOTAL,
    S.SILVER_GROSS_TOTAL,
    G.GOLD_GROSS_TOTAL,

    CASE
        WHEN B.BRONZE_GROSS_TOTAL = S.SILVER_GROSS_TOTAL
        THEN TRUE
        ELSE FALSE
    END AS RECONCILED_FLAG

FROM BRONZE_TOTAL B
CROSS JOIN SILVER_TOTAL S
CROSS JOIN GOLD_TOTAL G;
