USE WAREHOUSE PROJECT_13B_WH;
USE DATABASE PROJECT_13B_DB;
USE SCHEMA PROJECT_13B_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE='CSV'
SKIP_HEADER=1;

CREATE OR REPLACE STAGE hospital_stage
FILE_FORMAT=CSV_FORMAT;

LIST @hospital_stage;

-------------RAW TABLE CREATION
CREATE OR REPLACE TABLE RAW_HOSPITAL_HIERARCHY(
    HOSPITAL_ID NUMBER,
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    NETWORK_ID NUMBER,
    NETWORK_NAME VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);

CREATE OR REPLACE TABLE RAW_TREATMENT_HIERARCHY
(
    TREATMENT_ID NUMBER,
    TREATMENT_NAME VARCHAR(100),
    DIAGNOSIS_GROUP_ID VARCHAR(50),
    DIAGNOSIS_GROUP_NAME VARCHAR(100),
    STANDARD_COST NUMBER(12,2)
);

CREATE OR REPLACE TABLE RAW_PATIENTS
(
    PATIENT_ID NUMBER,
    PATIENT_NAME VARCHAR(100),
    GENDER VARCHAR(20),
    AGE NUMBER,
    CITY VARCHAR(50)
);

CREATE OR REPLACE TABLE RAW_INSURANCE_CLAIMS
(
    CLAIM_ID VARCHAR(50),
    CLAIM_DATE DATE,
    PATIENT_ID NUMBER,
    HOSPITAL_ID NUMBER,
    TREATMENT_ID NUMBER,
    CLAIMED_AMOUNT NUMBER(12,2),
    APPROVED_AMOUNT NUMBER(12,2)
);

----------------VERIFYING
SELECT COUNT(*) FROM RAW_HOSPITAL_HIERARCHY;

SELECT COUNT(*) FROM RAW_TREATMENT_HIERARCHY;

SELECT COUNT(*) FROM RAW_PATIENTS;

SELECT COUNT(*) FROM RAW_INSURANCE_CLAIMS;

-------------loading data
COPY INTO RAW_HOSPITAL_HIERARCHY
FROM @hospital_stage/hospital_hierarchy.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RAW_TREATMENT_HIERARCHY
FROM @hospital_stage/treatment_hierarchy.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RAW_PATIENTS
FROM @hospital_stage/patients.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RAW_INSURANCE_CLAIMS
FROM @hospital_stage/insurance_claims.csv
FILE_FORMAT = CSV_FORMAT;

--------------STAR SCEHMA TABLE CREATION
CREATE OR REPLACE TABLE STAR_DIM_HOSPITAL
(
    HOSPITAL_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    HOSPITAL_ID NUMBER,
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    NETWORK_NAME VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);

CREATE OR REPLACE TABLE STAR_DIM_TREATMENT
(
    TREATMENT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TREATMENT_ID NUMBER,
    TREATMENT_NAME VARCHAR(100),
    DIAGNOSIS_GROUP_NAME VARCHAR(50),
    STANDARD_COST NUMBER(12,2)
);

------------------LOADING STAR TABLES
INSERT INTO STAR_DIM_HOSPITAL
(
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    NETWORK_NAME,
    NETWORK_DIRECTOR
)
SELECT
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    NETWORK_NAME,
    NETWORK_DIRECTOR
FROM RAW_HOSPITAL_HIERARCHY;

------------VERIFYING
SELECT *
FROM STAR_DIM_HOSPITAL
ORDER BY HOSPITAL_ID;

INSERT INTO STAR_DIM_TREATMENT
(
    TREATMENT_ID,
    TREATMENT_NAME,
    DIAGNOSIS_GROUP_NAME,
    STANDARD_COST
)
SELECT
    TREATMENT_ID,
    TREATMENT_NAME,
    DIAGNOSIS_GROUP_NAME,
    STANDARD_COST
FROM RAW_TREATMENT_HIERARCHY;

----VERIFYING
SELECT *
FROM STAR_DIM_TREATMENT
ORDER BY TREATMENT_ID;

-------------STAR FACT TABLE CREATION
CREATE OR REPLACE TABLE STAR_FACT_CLAIMS
(
    CLAIM_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CLAIM_ID VARCHAR(50),
    CLAIM_DATE DATE,
    PATIENT_ID NUMBER,
    HOSPITAL_KEY NUMBER,
    TREATMENT_KEY NUMBER,
    CLAIMED_AMOUNT NUMBER(12,2),
    APPROVED_AMOUNT NUMBER(12,2),

    CONSTRAINT FK_STAR_HOSPITAL
        FOREIGN KEY (HOSPITAL_KEY)
        REFERENCES STAR_DIM_HOSPITAL(HOSPITAL_KEY),

    CONSTRAINT FK_STAR_TREATMENT
        FOREIGN KEY (TREATMENT_KEY)
        REFERENCES STAR_DIM_TREATMENT(TREATMENT_KEY)
);

------------------LOADING DATA
INSERT INTO STAR_FACT_CLAIMS
(
    CLAIM_ID,
    CLAIM_DATE,
    PATIENT_ID,
    HOSPITAL_KEY,
    TREATMENT_KEY,
    CLAIMED_AMOUNT,
    APPROVED_AMOUNT
)
SELECT
    C.CLAIM_ID,
    C.CLAIM_DATE,
    C.PATIENT_ID,
    H.HOSPITAL_KEY,
    T.TREATMENT_KEY,
    C.CLAIMED_AMOUNT,
    C.APPROVED_AMOUNT
FROM RAW_INSURANCE_CLAIMS C
JOIN STAR_DIM_HOSPITAL H
    ON C.HOSPITAL_ID = H.HOSPITAL_ID
JOIN STAR_DIM_TREATMENT T
    ON C.TREATMENT_ID = T.TREATMENT_ID;

-------------VERIFYING
SELECT *
FROM STAR_FACT_CLAIMS
ORDER BY CLAIM_DATE;


------------STAR SCHEMA ANALYSIS
SELECT T.DIAGNOSIS_GROUP_NAME,
SUM(F.CLAIMED_AMOUNT) AS TOTAL_CLAIMED_AMOUNT,
SUM(F.APPROVED_AMOUNT)AS TOTAL_APPROVED_AMOUNT,
FROM STAR_FACT_CLAIMS F
JOIN STAR_DIM_TREATMENT T
ON F.TREATMENT_KEY=T.TREATMENT_KEY
GROUP BY T.DIAGNOSIS_GROUP_NAME
ORDER BY T.DIAGNOSIS_GROUP_NAME;


-------hopsital metwrok director performance
SELECT H.NETWORK_DIRECTOR,
COUNT(F.CLAIM_ID) AS TOTAL_CLAIMS_HANDLED,
SUM(F.APPROVED_AMOUNT)AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS F
JOIN STAR_DIM_HOSPITAL H
ON F.HOSPITAL_KEY=H.HOSPITAL_KEY
GROUP BY H.NETWORK_DIRECTOR
ORDER BY H.NETWORK_DIRECTOR;

---------star schema maintenance test
SELECT HOSPITAL_KEY,HOSPITAL_ID,HOSPITAL_NAME,
NETWORK_NAME,NETWORK_DIRECTOR
FROM STAR_DIM_HOSPITAL
WHERE NETWORK_NAME='Apollo Healthcare Group';

---------------here we get same doctor name for that complete group so when we update also it completely gets updated.Like both the rows get updated.

------------Updating the star schema
UPDATE STAR_DIM_HOSPITAL
SET NETWORK_DIRECTOR = 'Dr. Anand'
WHERE NETWORK_NAME = 'Apollo Healthcare Group'
  AND NETWORK_DIRECTOR = 'Dr. Ramesh';

---------------verifying the number of updated rows
SELECT
    COUNT(*) AS UPDATED_ROWS
FROM STAR_DIM_HOSPITAL
WHERE NETWORK_NAME = 'Apollo Healthcare Group'
  AND NETWORK_DIRECTOR = 'Dr. Anand';

---------------------SNOWFLAKE SCHEMA CREATION 
CREATE OR REPLACE TABLE SNOW_DIM_NETWORK(
NETWORK_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
NETWORK_ID NUMBER,
NETWORK_NAME VARCHAR(100),
NETWORK_DIRECTOR VARCHAR(100)
)

CREATE OR REPLACE TABLE SNOW_DIM_HOSPITAL
(
HOSPITAL_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
HOSPITAL_ID NUMBER,
HOSPITAL_NAME VARCHAR(50),
CITY VARCHAR(50),
STATE VARCHAR(50),
NETWORK_KEY NUMBER,
CONSTRAINT FK_SNOW_HOSPITAL_NETWORK
        FOREIGN KEY (NETWORK_KEY)
        REFERENCES SNOW_DIM_NETWORK(NETWORK_KEY)
);

CREATE OR REPLACE TABLE SNOW_DIM_DIAGNOSIS_GROUP
(
    DIAGNOSIS_GROUP_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    DIAGNOSIS_GROUP_ID VARCHAR(50),
    DIAGNOSIS_GROUP_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE SNOW_DIM_TREATMENT
(
    TREATMENT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TREATMENT_ID NUMBER,
    TREATMENT_NAME VARCHAR(100),
    STANDARD_COST NUMBER(12,2),
    DIAGNOSIS_GROUP_KEY NUMBER,

    CONSTRAINT FK_SNOW_TREATMENT_DIAGNOSIS
        FOREIGN KEY (DIAGNOSIS_GROUP_KEY)
        REFERENCES SNOW_DIM_DIAGNOSIS_GROUP(DIAGNOSIS_GROUP_KEY)
);

-------------SNOWFLAKE FACT TABLE CREATION
CREATE OR REPLACE TABLE SNOW_FACT_CLAIMS
(
    CLAIM_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CLAIM_ID VARCHAR(50),
    CLAIM_DATE DATE,
    PATIENT_ID NUMBER,
    HOSPITAL_KEY NUMBER,
    TREATMENT_KEY NUMBER,
    CLAIMED_AMOUNT NUMBER(12,2),
    APPROVED_AMOUNT NUMBER(12,2),

    CONSTRAINT FK_SNOW_FACT_HOSPITAL
        FOREIGN KEY (HOSPITAL_KEY)
        REFERENCES SNOW_DIM_HOSPITAL(HOSPITAL_KEY),

    CONSTRAINT FK_SNOW_FACT_TREATMENT
        FOREIGN KEY (TREATMENT_KEY)
        REFERENCES SNOW_DIM_TREATMENT(TREATMENT_KEY)
);

-------------------LOADING DATA INTO THESE TABLES
INSERT INTO SNOW_DIM_NETWORK
(
    NETWORK_ID,
    NETWORK_NAME,
    NETWORK_DIRECTOR
)
SELECT DISTINCT
    NETWORK_ID,
    NETWORK_NAME,
    NETWORK_DIRECTOR
FROM RAW_HOSPITAL_HIERARCHY;

INSERT INTO SNOW_DIM_HOSPITAL
(
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    NETWORK_KEY
)
SELECT
    H.HOSPITAL_ID,
    H.HOSPITAL_NAME,
    H.CITY,
    H.STATE,
    N.NETWORK_KEY
FROM RAW_HOSPITAL_HIERARCHY H
JOIN SNOW_DIM_NETWORK N
    ON H.NETWORK_ID = N.NETWORK_ID;


INSERT INTO SNOW_DIM_DIAGNOSIS_GROUP
(
    DIAGNOSIS_GROUP_ID,
    DIAGNOSIS_GROUP_NAME
)
SELECT DISTINCT
    DIAGNOSIS_GROUP_ID,
    DIAGNOSIS_GROUP_NAME
FROM RAW_TREATMENT_HIERARCHY;

INSERT INTO SNOW_DIM_TREATMENT
(
    TREATMENT_ID,
    TREATMENT_NAME,
    STANDARD_COST,
    DIAGNOSIS_GROUP_KEY
)
SELECT
    T.TREATMENT_ID,
    T.TREATMENT_NAME,
    T.STANDARD_COST,
    D.DIAGNOSIS_GROUP_KEY
FROM RAW_TREATMENT_HIERARCHY T
JOIN SNOW_DIM_DIAGNOSIS_GROUP D
    ON T.DIAGNOSIS_GROUP_ID = D.DIAGNOSIS_GROUP_ID;

-------------FACT CLAIMS
INSERT INTO SNOW_FACT_CLAIMS
(
    CLAIM_ID,
    CLAIM_DATE,
    PATIENT_ID,
    HOSPITAL_KEY,
    TREATMENT_KEY,
    CLAIMED_AMOUNT,
    APPROVED_AMOUNT
)
SELECT
    C.CLAIM_ID,
    C.CLAIM_DATE,
    C.PATIENT_ID,
    H.HOSPITAL_KEY,
    T.TREATMENT_KEY,
    C.CLAIMED_AMOUNT,
    C.APPROVED_AMOUNT
FROM RAW_INSURANCE_CLAIMS C
JOIN SNOW_DIM_HOSPITAL H
    ON C.HOSPITAL_ID = H.HOSPITAL_ID
JOIN SNOW_DIM_TREATMENT T
    ON C.TREATMENT_ID = T.TREATMENT_ID;

-------------SNOWFLAKE SPECIALITY ANALYSIS
SELECT
    D.DIAGNOSIS_GROUP_NAME,
    SUM(F.CLAIMED_AMOUNT) AS TOTAL_CLAIMED_AMOUNT,
    SUM(F.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS F
JOIN SNOW_DIM_TREATMENT T
    ON F.TREATMENT_KEY = T.TREATMENT_KEY
JOIN SNOW_DIM_DIAGNOSIS_GROUP D
    ON T.DIAGNOSIS_GROUP_KEY = D.DIAGNOSIS_GROUP_KEY
GROUP BY D.DIAGNOSIS_GROUP_NAME
ORDER BY D.DIAGNOSIS_GROUP_NAME;

-----------NETWORK DIRECTOR ANALYSIS
SELECT
    N.NETWORK_DIRECTOR,
    COUNT(F.CLAIM_ID) AS TOTAL_CLAIMS_HANDLED,
    SUM(F.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS F
JOIN SNOW_DIM_HOSPITAL H
    ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
JOIN SNOW_DIM_NETWORK N
    ON H.NETWORK_KEY = N.NETWORK_KEY
GROUP BY N.NETWORK_DIRECTOR
ORDER BY N.NETWORK_DIRECTOR;

------------SNOWFLAKE MAINTENANCE TEST

-----1.verifying the network 10
SELECT *
FROM SNOW_DIM_NETWORK
WHERE NETWORK_ID = 10;

-----------2.updating the network director
UPDATE SNOW_DIM_NETWORK
SET NETWORK_DIRECTOR = 'Dr. Anand'
WHERE NETWORK_ID = 10
  AND NETWORK_DIRECTOR = 'Dr. Ramesh';

------------here network information got updated only for one row becuase here we are normalising network information so only 1 row gets updated.