USE WAREHOUSE PROJECT9_WH;
USE DATABASE PROJECT_9_DB;
USE SCHEMA PROJE9_SCHEMA;


---CREATION OF FILE FORMAT

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE='CSV'
SKIP_HEADER=1;

---STAGE CREATION
CREATE OR REPLACE STAGE CUSTOMER_HISTORY_STAGE
FILE_FORMAT=CSV_FORMAT;

---TABLE CREATION and loading for scd type 1
CREATE OR REPLACE TABLE SCD_TYPE1
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);

COPY INTO SCD_TYPE1
(CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT)
FROM @CUSTOMER_HISTORY_STAGE/customer_initial1.csv
FILE_FORMAT=CSV_FORMAT;

--------------UPDATING THE DETAILS
SELECT *
FROM SCD_TYPE1
ORDER BY CUSTOMER_ID;

UPDATE SCD_TYPE1
SET
    CITY = 'Bengaluru',
    STATE = 'Karnataka',
    MEMBERSHIP = 'Gold',
    SEGMENT = 'Premium'
WHERE CUSTOMER_ID = 101;

Select * from SCD_TYPE1 where
CUSTOMER_ID=101;

UPDATE SCD_TYPE1
SET
    CITY = 'Chennai',
    STATE = 'Tamil Nadu',
    MEMBERSHIP = 'Gold',
    SEGMENT = 'Premium'
where CUSTOMER_ID=103;

Select * from SCD_TYPE1 where
CUSTOMER_ID=103;

UPDATE SCD_TYPE1
SET
    MEMBERSHIP = 'Platinum',
    SEGMENT = 'Premium'
WHERE CUSTOMER_ID=104;

Select * from SCD_TYPE1
where CUSTOMER_ID=104;

-------------VALIDATING
SELECT * FROM SCD_TYPE1;

----------------TABLE CREATION AND LOADING FOR SCD TYPE 2

CREATE OR REPLACE TABLE SCD_TYPE2
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE DEFAULT TO_DATE('2026-01-01'),
    EXPIRY_DATE DATE DEFAULT TO_DATE('9999-12-31'),
    IS_CURRENT BOOLEAN DEFAULT TRUE
);

TRUNCATE TABLE SCD_TYPE2;

COPY INTO SCD_TYPE2
(CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT)
FROM @CUSTOMER_HISTORY_STAGE/customer_initial1.csv
FILE_FORMAT=CSV_FORMAT;

Select * from SCD_TYPE2;

Select * from SCD_TYPE2
WHERE CUSTOMER_ID=101;

----Expiring the existing record
UPDATE SCD_TYPE2
SET
    EXPIRY_DATE = '2026-03-31',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 101
  AND IS_CURRENT = TRUE;

-----------validating 
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM SCD_TYPE2
WHERE CUSTOMER_ID = 101;


----------CREATING UPDATES TABLE AND LOADING
CREATE OR REPLACE TABLE CUSTOMER_UPDATES
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);
COPY INTO CUSTOMER_UPDATES
FROM @CUSTOMER_HISTORY_STAGE/customer_update1.csv
FILE_FORMAT = CSV_FORMAT;


-------------inserting new row for changed 101
INSERT INTO SCD_TYPE2
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    TO_DATE('9999-12-31'),
    TRUE
FROM CUSTOMER_UPDATES
WHERE CUSTOMER_ID = 101;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM SCD_TYPE2
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;

----------------For Customer 103
UPDATE SCD_TYPE2
SET
    EXPIRY_DATE = '2026-04-04',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103
  AND IS_CURRENT = TRUE;

Select * from SCD_TYPE2;

INSERT INTO SCD_TYPE2
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    TO_DATE('9999-12-31'),
    TRUE
FROM CUSTOMER_UPDATES
WHERE CUSTOMER_ID = 103;

Select * from SCD_TYPE2;

----------------------------For Customer 104
UPDATE SCD_TYPE2
SET
    EXPIRY_DATE = '2026-04-09',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104
  AND IS_CURRENT = TRUE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM SCD_TYPE2
WHERE CUSTOMER_ID = 104;

INSERT INTO SCD_TYPE2
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    TO_DATE('9999-12-31'),
    TRUE
FROM CUSTOMER_UPDATES
WHERE CUSTOMER_ID = 104;

-------------------Final Output
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM SCD_TYPE2
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;
