USE WAREHOUSE PROJECT_13_WH;
USE DATABASE PROJECT_13_DB;
USE SCHEMA PROJECT_13_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE='CSV'
SKIP_HEADER=1;

------------STAGE CREATION
CREATE OR REPLACE STAGE cus_stage
FILE_FORMAT= CSV_FORMAT;

------------CREATING RAW TABLES
CREATE OR REPLACE TABLE RAW_REGIONS_AND_STORES
(
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION_NAME VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);

CREATE OR REPLACE TABLE RAW_PRODUCT_HIERARCHY
(
  PRODUCT_ID NUMBER,
  PRODUCT_NAME VARCHAR(100),
  SUBCATEGORY_NAME VARCHAR(50),
  CATEGORY_NAME VARCHAR(50),
  UNIT_PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE RAW_SALES_TRANSACTIONS(
 TRANSACTION_ID VARCHAR(50),
 TRANSACTION_DATE DATE,
    CUSTOMER_ID NUMBER,
    STORE_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE RAW_CUSTOMERS(
 CUSTOMER_ID NUMBER,
 CUSTOMER_NAME VARCHAR(100),
 CITY VARCHAR(50),
 STATE VARCHAR(50)
);

------------COPYING CSV DATA INTO RAW TABLES
COPY INTO RAW_REGIONS_AND_STORES
FROM @cus_stage/regions_and_stores.csv
FILE_FORMAT=CSV_FORMAT;

COPY INTO RAW_PRODUCT_HIERARCHY
FROM @cus_stage/product_hierarchy.csv
FILE_FORMAT=CSV_FORMAT;

COPY INTO RAW_CUSTOMERS
FROM @cus_stage/customers.csv
FILE_FORMAT=CSV_FORMAT;

COPY INTO RAW_SALES_TRANSACTIONS
FROM @cus_stage/sales_tranasctions.csv
FILE_FORMAT=CSV_FORMAT;

--------------CREATING STAR DIMENSION TABLES
CREATE OR REPLACE TABLE STAR_DIM_STORE(
STORE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION_NAME VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)

);
---LOADING DATA
INSERT INTO STAR_DIM_STORE
(
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_NAME,
    REGIONAL_MANAGER
)
SELECT
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_NAME,
    REGIONAL_MANAGER
FROM RAW_REGIONS_AND_STORES;

---VALIDATING
SELECT * 
FROM STAR_DIM_STORE
ORDER BY STORE_ID;

CREATE OR REPLACE TABLE STAR_DIM_PRODUCT(
PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_NAME VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);
INSERT INTO STAR_DIM_PRODUCT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    SUBCATEGORY_NAME,
    CATEGORY_NAME,
    UNIT_PRICE
)
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    SUBCATEGORY_NAME,
    CATEGORY_NAME,
    UNIT_PRICE
FROM RAW_PRODUCT_HIERARCHY;

SELECT * FROM STAR_DIM_PRODUCT
ORDER BY PRODUCT_ID;

---------------CREATING STAR FACT TABLES
CREATE OR REPLACE TABLE STAR_FACT_SALES(
SALES_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
TRANSACTION_ID VARCHAR(50),
TRANSACTION_DATE DATE,
CUSTOMER_ID NUMBER,
STORE_KEY NUMBER,
PRODUCT_KEY NUMBER,
QUANTITY NUMBER,
TOTAL_AMOUNT NUMBER(12,2)
);

INSERT INTO STAR_FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_ID,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    R.TRANSACTION_ID,
    R.TRANSACTION_DATE,
    R.CUSTOMER_ID,
    S.STORE_KEY,
    P.PRODUCT_KEY,
    R.QUANTITY,
    R.QUANTITY * R.UNIT_PRICE
FROM RAW_SALES_TRANSACTIONS R
JOIN STAR_DIM_STORE S
    ON R.STORE_ID = S.STORE_ID
JOIN STAR_DIM_PRODUCT P
    ON R.PRODUCT_ID = P.PRODUCT_ID;

---------VALIDATING
SELECT * FROM STAR_FACT_SALES
ORDER BY TRANSACTION_ID;

------------------STAR SCHEMA ANALYTICS
SELECT
    S.REGION_NAME,
    P.CATEGORY_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM STAR_FACT_SALES F
JOIN STAR_DIM_STORE S
    ON F.STORE_KEY = S.STORE_KEY
JOIN STAR_DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY
GROUP BY
    S.REGION_NAME,
    P.CATEGORY_NAME
ORDER BY
    S.REGION_NAME,
    P.CATEGORY_NAME;

---------------SNOWFLAKE TABLE CREATION
CREATE OR REPLACE TABLE SNOW_DIM_REGION
(
    REGION_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    REGION_NAME VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);

CREATE OR REPLACE TABLE SNOW_DIM_STORE
(
    STORE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION_KEY NUMBER
);
INSERT INTO SNOW_DIM_REGION(
REGION_NAME,
REGIONAL_MANAGER
)
SELECT DISTINCT REGION_NAME,REGIONAL_MANAGER
FROM RAW_REGIONS_AND_STORES;

INSERT INTO SNOW_DIM_STORE
(
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_KEY
)
SELECT
    R.STORE_ID,
    R.STORE_NAME,
    R.CITY,
    R.STATE,
    RG.REGION_KEY
FROM RAW_REGIONS_AND_STORES R
JOIN SNOW_DIM_REGION RG
    ON R.REGION_NAME = RG.REGION_NAME
   AND R.REGIONAL_MANAGER = RG.REGIONAL_MANAGER;

---------VALIDATING
SELECT *
FROM SNOW_DIM_STORE
ORDER BY STORE_ID;

---------------CREATING SNOWFLAKE PRODUCT HIERARCHY
CREATE OR REPLACE TABLE SNOW_DIM_CATEGORY
(
    CATEGORY_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50)
);

INSERT INTO SNOW_DIM_CATEGORY
(
    CATEGORY_NAME
)
SELECT DISTINCT
    CATEGORY_NAME
FROM RAW_PRODUCT_HIERARCHY;

SELECT *
FROM SNOW_DIM_CATEGORY
ORDER BY CATEGORY_KEY;

-------------CREATING SUB CATEGORY
CREATE OR REPLACE TABLE SNOW_DIM_SUBCATEGORY
(
    SUBCATEGORY_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_KEY NUMBER
);

INSERT INTO SNOW_DIM_SUBCATEGORY
(
    SUBCATEGORY_NAME,
    CATEGORY_KEY
)
SELECT DISTINCT
    R.SUBCATEGORY_NAME,
    C.CATEGORY_KEY
FROM RAW_PRODUCT_HIERARCHY R
JOIN SNOW_DIM_CATEGORY C
    ON R.CATEGORY_NAME = C.CATEGORY_NAME;

-- -------Create SNOW_DIM_PRODUCT
CREATE OR REPLACE TABLE SNOW_DIM_PRODUCT
(
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    UNIT_PRICE NUMBER(10,2),
    SUBCATEGORY_KEY NUMBER
);

INSERT INTO SNOW_DIM_PRODUCT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    UNIT_PRICE,
    SUBCATEGORY_KEY
)
SELECT
    R.PRODUCT_ID,
    R.PRODUCT_NAME,
    R.UNIT_PRICE,
    S.SUBCATEGORY_KEY
FROM RAW_PRODUCT_HIERARCHY R
JOIN SNOW_DIM_SUBCATEGORY S
    ON R.SUBCATEGORY_NAME = S.SUBCATEGORY_NAME;

-------------------CREATE SNOW_FACT_SALES
CREATE OR REPLACE TABLE SNOW_FACT_SALES
(
    SALES_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID NUMBER,
    STORE_KEY NUMBER,
    PRODUCT_KEY NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2)
);
------loading into 
INSERT INTO SNOW_FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_ID,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    R.TRANSACTION_ID,
    R.TRANSACTION_DATE,
    R.CUSTOMER_ID,
    S.STORE_KEY,
    P.PRODUCT_KEY,
    R.QUANTITY,
    R.QUANTITY * R.UNIT_PRICE
FROM RAW_SALES_TRANSACTIONS R
JOIN SNOW_DIM_STORE S
    ON R.STORE_ID = S.STORE_ID
JOIN SNOW_DIM_PRODUCT P
    ON R.PRODUCT_ID = P.PRODUCT_ID;


--------------Snowflake Analytics Query
SELECT
    R.REGION_NAME,
    C.CATEGORY_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE

FROM SNOW_FACT_SALES F

JOIN SNOW_DIM_STORE S
    ON F.STORE_KEY = S.STORE_KEY

JOIN SNOW_DIM_REGION R
    ON S.REGION_KEY = R.REGION_KEY

JOIN SNOW_DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY

JOIN SNOW_DIM_SUBCATEGORY SC
    ON P.SUBCATEGORY_KEY = SC.SUBCATEGORY_KEY

JOIN SNOW_DIM_CATEGORY C
    ON SC.CATEGORY_KEY = C.CATEGORY_KEY

GROUP BY
    R.REGION_NAME,
    C.CATEGORY_NAME

ORDER BY
    R.REGION_NAME,
    C.CATEGORY_NAME;

----------------REGIONAL MANAGER SALES REPORT
SELECT
    S.REGIONAL_MANAGER,
    SUM(F.QUANTITY) AS TOTAL_ITEMS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES_AMOUNT
FROM STAR_FACT_SALES F
JOIN STAR_DIM_STORE S
    ON F.STORE_KEY = S.STORE_KEY
GROUP BY
    S.REGIONAL_MANAGER
ORDER BY
    S.REGIONAL_MANAGER;

--------------------FINAL AUDIT
SELECT
    'Star Schema' AS SCHEMA_TYPE,
    'STAR_DIM_STORE' AS TABLE_NAME,
    COUNT(*) AS RECORD_COUNT
FROM STAR_DIM_STORE

UNION ALL

SELECT
    'Star Schema',
    'STAR_DIM_PRODUCT',
    COUNT(*)
FROM STAR_DIM_PRODUCT

UNION ALL

SELECT
    'Star Schema',
    'STAR_FACT_SALES',
    COUNT(*)
FROM STAR_FACT_SALES

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_REGION',
    COUNT(*)
FROM SNOW_DIM_REGION

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_STORE',
    COUNT(*)
FROM SNOW_DIM_STORE

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_CATEGORY',
    COUNT(*)
FROM SNOW_DIM_CATEGORY

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_SUBCATEGORY',
    COUNT(*)
FROM SNOW_DIM_SUBCATEGORY

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_PRODUCT',
    COUNT(*)
FROM SNOW_DIM_PRODUCT

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_FACT_SALES',
    COUNT(*)
FROM SNOW_FACT_SALES;